### ISSUE TITLE
Ecto.Repo.Schema.insert! returns an error

### ISSUE THREAD

**Issue by Netherdrake** [metachaos-systems/glasnost#16]
```
glasnost_1  |     (ecto) lib/ecto/repo/schema.ex:125: Ecto.Repo.Schema.insert!/4
glasnost_1  | 22:34:57.221 [error] Process #PID<0.26061.0> raised an exception
glasnost_1  | ** (Ecto.ChangeError) value `[[1, "0.16.4"]]` for `Glasnost.Golos.Block.extensions` in `insert` does not match type {:array, :map}
glasnost_1  |     (ecto) lib/ecto/repo/schema.ex:788: Ecto.Repo.Schema.dump_field!/6
glasnost_1  |     (ecto) lib/ecto/repo/schema.ex:797: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
glasnost_1  |     (stdlib) lists.erl:1263: :lists.foldl/3
glasnost_1  |     (ecto) lib/ecto/repo/schema.ex:795: Ecto.Repo.Schema.dump_fields!/5
glasnost_1  |     (ecto) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.dump_changes!/6
glasnost_1  |     (ecto) lib/ecto/repo/schema.ex:207: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
glasnost_1  |     (ecto) lib/ecto/repo/schema.ex:125: Ecto.Repo.Schema.insert!/4
```

**Comment by ontofractal** [comment]
Thanks for the report, it's a bit strange as I remember fixing this bug some time ago. I can't reproduce it neither with latest docker image nor without docker. I've made changes to the schemas to make it easier to find a source of this bug.
